'use client';

import { useRef, useState } from 'react';
import Link from 'next/link';
import { AppearanceControls, ImageAssignments } from '@/components/personalization';

const sections=['Overview','Reviews','Features','Essays','Hidden Gems','Homepage','Media','Newsletter','Review Requests','Site Settings'];
const scoreCategories=['Direction','Acting','Story','Cinematography','Score','Editing','Emotional Impact'];

export default function Admin(){
  const editor=useRef<HTMLElement>(null); const [notice,setNotice]=useState('');
  const [draft,setDraft]=useState({title:'',director:'',year:'',genre:'',premise:'',body:'',rating:''}); const [stars,setStars]=useState<Record<string,number>>({});
  const go=(title='')=>{setDraft(x=>({...x,title}));editor.current?.scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>document.getElementById('movie-title')?.focus(),250)};
  const save=(published:boolean)=>setNotice(published?'Review is ready to publish. Connect an editor account to make it permanent.':'Draft saved for this browser session.');
  return <main className="admin"><aside><div className="brand">FILMCRIQE<span>Editorial desk</span></div><nav>{sections.map((x,i)=><a className={i===0?'active':''} href={`#${x.toLowerCase().replaceAll(' ','-')}`} key={x}>{x}</a>)}</nav><Link href="/">View publication →</Link></aside><section><header><div><div className="eyebrow">Private editorial dashboard</div><h1 className="display">Overview</h1></div><button className="button" type="button" onClick={()=>go()}>New Review</button></header><div className="admin-stats"><Stat n="01" label="Published reviews"/><Stat n="03" label="Published articles"/><Stat n="02" label="Hidden gems"/><Stat n="00" label="Drafts"/></div><AppearanceControls/><ImageAssignments/><div className="admin-grid"><section><div className="eyebrow">Recent content</div><h2 className="display">Editorial queue</h2><div className="admin-row"><b>After the Last Light</b><span>Review · Published</span><button type="button" onClick={()=>go('After the Last Light')}>Edit</button></div><div className="admin-row"><b>The Sound of Weather</b><span>Feature · Published</span><button type="button" onClick={()=>go('The Sound of Weather')}>Edit</button></div></section><section id="media"><div className="eyebrow">Media</div><h2 className="display">Photography library</h2><div className="upload">Choose a photograph in Image Assignments to place it across the publication.<small>Publishing media permanently requires an authenticated Supabase editor account.</small></div></section></div><section className="editor" ref={editor}><div className="eyebrow">Review editor</div><h2 className="display">Draft a review</h2><div className="editor-fields"><Field id="movie-title" label="Movie title" value={draft.title} onChange={title=>setDraft(x=>({...x,title}))}/><Field label="Director" value={draft.director} onChange={director=>setDraft(x=>({...x,director}))}/><Field label="Release year" value={draft.year} onChange={year=>setDraft(x=>({...x,year}))}/><Field label="Genre" value={draft.genre} onChange={genre=>setDraft(x=>({...x,genre}))}/><Field label="Premise" value={draft.premise} onChange={premise=>setDraft(x=>({...x,premise}))} full/><Field label="Review body" value={draft.body} onChange={body=>setDraft(x=>({...x,body}))} full area/><Field label="Overall Rating (0–10)" value={draft.rating} onChange={rating=>setDraft(x=>({...x,rating}))}/><div className="form-field"><label>SceneScore categories</label><div className="star-select">{scoreCategories.map(name=><button type="button" key={name} onClick={()=>setStars(x=>({...x,[name]:((x[name]||0)+1)%6}))}>{name} {'★'.repeat(stars[name]||0)}{'☆'.repeat(5-(stars[name]||0))}</button>)}</div></div></div><button className="button ghost" type="button" onClick={()=>save(false)}>Save draft</button> <button className="button" type="button" onClick={()=>save(true)}>Publish</button>{notice&&<p className="metadata" role="status">{notice}</p>}</section></section></main>}
function Stat({n,label}:{n:string;label:string}){return <div><strong>{n}</strong><span>{label}</span></div>}
function Field({id,label,value,onChange,full,area}:{id?:string;label:string;value:string;onChange:(value:string)=>void;full?:boolean;area?:boolean}){const field=id||label;return <div className={`form-field ${full?'full':''}`}><label htmlFor={field}>{label}</label>{area?<textarea id={field} value={value} onChange={e=>onChange(e.target.value)}/>:<input id={field} value={value} onChange={e=>onChange(e.target.value)}/>}</div>}
