'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { supabaseBrowser as db } from '@/lib/supabase-browser';
import { ContentImageUpload } from '@/components/content-image-upload';

type Status = 'draft' | 'published' | 'archived';
type ContentType = 'review' | 'feature' | 'essay' | 'interview' | 'news' | 'industry' | 'awards' | 'production' | 'hidden-gem';
type RecordItem = { id:string; title:string; slug:string; type:ContentType; status:Status; dek:string|null; published_at:string|null; is_featured:boolean; release_year:number|null; director:string|null; genre:string|null; review_meta:{overall?:number; categories?:Record<string,number>}|null; hero_path:string|null; hero_alt:string|null; body:unknown; tags:string[]|null; category:string|null; scheduled_at:string|null };
const kinds:ContentType[]=['review','feature','essay','interview','news','industry','awards','production','hidden-gem'];
const scoreCategories=['Direction','Acting','Story','Cinematography','Score','Editing','Emotional Impact'];
const empty={title:'',slug:'',type:'review' as ContentType,status:'draft' as Status,dek:'',release_year:'',director:'',genre:'',rating:'',body:'',tags:'',category:'',hero_path:'',hero_alt:'',featured:false,scheduled_at:''};
function slugify(value:string){return value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}

export function AdminContentManager(){
  const [admin,setAdmin]=useState(false); const [items,setItems]=useState<RecordItem[]>([]); const [form,setForm]=useState(empty); const [editing,setEditing]=useState<string|null>(null); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);
  async function load(){if(!db)return;const{data,error}=await db.from('content').select('id,title,slug,type,status,dek,published_at,is_featured,release_year,director,genre,review_meta,hero_path,hero_alt,body,tags,category,scheduled_at').order('updated_at',{ascending:false});if(error){setMessage(`Could not load editorial content: ${error.message}`);return}setItems((data||[]) as RecordItem[])}
  useEffect(()=>{const client=db;if(!client)return;let on=true;client.auth.getUser().then(async({data})=>{if(!data.user)return;const{data:profile}=await client.from('profiles').select('role').eq('id',data.user.id).maybeSingle();if(on&&profile?.role==='admin'){setAdmin(true);load()}});return()=>{on=false}},[]);
  const title = editing ? 'Edit story' : 'Create story';
  function set<K extends keyof typeof empty>(key:K,value:(typeof empty)[K]){setForm(x=>({...x,[key]:value}))}
  function begin(item?:RecordItem){if(!item){setEditing(null);setForm(empty);return}const paragraphs=Array.isArray(item.body)?(item.body as {text?:string}[]).map(x=>x.text||'').join('\n\n'):'';setEditing(item.id);setForm({title:item.title,slug:item.slug,type:item.type,status:item.status,dek:item.dek||'',release_year:item.release_year?.toString()||'',director:item.director||'',genre:item.genre||'',rating:item.review_meta?.overall?.toString()||'',body:paragraphs,tags:(item.tags||[]).join(', '),category:item.category||'',hero_path:item.hero_path||'',hero_alt:item.hero_alt||'',featured:item.is_featured,scheduled_at:item.scheduled_at?.slice(0,16)||''});document.getElementById('editor')?.scrollIntoView({behavior:'smooth',block:'start'})}
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!db||!admin)return;const slug=form.slug||slugify(form.title);if(!form.title||!slug){setMessage('A title is required.');return}const rating=Number(form.rating);if(form.type==='review'&&(!Number.isFinite(rating)||rating<0||rating>10)){setMessage('A review needs an overall rating from 0 to 10.');return}setBusy(true);const body=form.body.split(/\n\s*\n/).filter(Boolean).map(text=>({type:'paragraph',text}));const payload={title:form.title,slug,type:form.type,status:form.status,dek:form.dek||null,release_year:form.release_year?Number(form.release_year):null,director:form.director||null,genre:form.genre||null,category:form.category||null,tags:form.tags.split(',').map(x=>x.trim()).filter(Boolean),hero_path:form.hero_path||null,hero_alt:form.hero_alt||null,is_featured:form.featured,published_at:form.status==='published'?new Date().toISOString():null,scheduled_at:form.scheduled_at?new Date(form.scheduled_at).toISOString():null,body,review_meta:form.type==='review'?{overall:rating,categories:Object.fromEntries(scoreCategories.map(x=>[x,4]))}:null};const query=editing?db.from('content').update(payload).eq('id',editing):db.from('content').insert(payload);const{error}=await query;setBusy(false);if(error){setMessage(`Could not save this story: ${error.message}`);return}setMessage(form.status==='published'?'Published — it will appear in the public archive.':'Draft saved securely.');begin();load()}
  async function remove(item:RecordItem){if(!db||!admin||!confirm(`Delete “${item.title}”? This cannot be undone.`))return;const{error}=await db.from('content').delete().eq('id',item.id);setMessage(error?`Could not delete: ${error.message}`:'Story deleted.');if(!error)load()}
  const list=useMemo(()=>items.map(item=><div className="admin-row" key={item.id}><b>{item.title}</b><span>{item.type} · {item.status}</span><button type="button" onClick={()=>begin(item)}>Edit</button><button type="button" onClick={()=>remove(item)}>Delete</button></div>),[items]);
  if(!admin)return <section className="admin-grid" id="reviews"><section><div className="eyebrow">Content management</div><h2 className="display">Editorial CMS</h2><p className="metadata">Sign in through Appearance to create, edit, publish, or delete FILMCRIQE stories.</p></section></section>;
  return <section className="cms" id="reviews"><div className="section-title"><div><div className="eyebrow">Content management</div><h2 className="display">Editorial CMS</h2></div><button className="button" type="button" onClick={()=>begin()}>New story</button></div><div className="admin-grid"><section><div className="eyebrow">Saved content</div><h3 className="display">Publication queue</h3>{list.length?list:<p className="metadata">No saved stories yet. Your existing publication remains visible while you build the live archive.</p>}</section><section id="editor" className="editor"><div className="eyebrow">{title}</div><h3 className="display">{form.title||'Untitled story'}</h3><form className="editor-fields" onSubmit={save}><Text label="Title" value={form.title} onChange={x=>{set('title',x);if(!editing)set('slug',slugify(x))}}/><Text label="URL slug" value={form.slug} onChange={x=>set('slug',slugify(x))}/><Select label="Content type" value={form.type} onChange={x=>set('type',x as ContentType)} options={kinds}/><Select label="Status" value={form.status} onChange={x=>set('status',x as Status)} options={['draft','published','archived']}/><Text label="Release year" value={form.release_year} onChange={x=>set('release_year',x)} type="number"/><Text label="Director" value={form.director} onChange={x=>set('director',x)}/><Text label="Genre" value={form.genre} onChange={x=>set('genre',x)}/><Text label="Category" value={form.category} onChange={x=>set('category',x)}/>{form.type==='review'&&<Text label="Overall Rating (0–10)" value={form.rating} onChange={x=>set('rating',x)} type="number" step="0.1"/>}<Text label="Tags (comma separated)" value={form.tags} onChange={x=>set('tags',x)} full/><Text label="Deck / excerpt" value={form.dek} onChange={x=>set('dek',x)} full/><Text label="Hero image URL" value={form.hero_path} onChange={x=>set('hero_path',x)} full/><ContentImageUpload onUploaded={url=>set('hero_path',url)}/><Text label="Hero image alt text" value={form.hero_alt} onChange={x=>set('hero_alt',x)} full/><Text label="Schedule (optional)" value={form.scheduled_at} onChange={x=>set('scheduled_at',x)} type="datetime-local"/><label className="form-field checkbox"><input type="checkbox" checked={form.featured} onChange={e=>set('featured',e.target.checked)}/> Feature this story on the homepage</label><Text label="Article body (separate paragraphs with a blank line)" value={form.body} onChange={x=>set('body',x)} full area/><div className="full"><button className="button" disabled={busy}>{busy?'Saving…':form.status==='published'?'Publish story':'Save draft'}</button>{editing&&<button className="button ghost" type="button" onClick={()=>begin()}>Cancel edit</button>}</div></form>{message&&<p className="metadata" role="status">{message}</p>}</section></div></section>
}
function Text({label,value,onChange,full,area,type='text',step}:{label:string;value:string;onChange:(x:string)=>void;full?:boolean;area?:boolean;type?:string;step?:string}){const id=`cms-${label.toLowerCase().replace(/[^a-z0-9]+/g,'-')}`;return <label className={`form-field ${full?'full':''}`} htmlFor={id}>{label}{area?<textarea id={id} value={value} onChange={e=>onChange(e.target.value)}/>:<input id={id} value={value} type={type} step={step} onChange={e=>onChange(e.target.value)}/>}</label>}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(x:string)=>void;options:string[]}){const id=`cms-${label.toLowerCase().replace(/[^a-z0-9]+/g,'-')}`;return <label className="form-field" htmlFor={id}>{label}<select id={id} value={value} onChange={e=>onChange(e.target.value)}>{options.map(x=><option key={x} value={x}>{x}</option>)}</select></label>}
