'use client';
import { FormEvent, useState } from 'react';
import { createClient } from '@supabase/supabase-js';

const url=process.env.NEXT_PUBLIC_SUPABASE_URL, key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
const db=url&&key?createClient(url,key):null;

export function NewsletterForm({compact=false}:{compact?:boolean}){const [message,setMessage]=useState('');async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget),email=String(form.get('email')||'').trim().toLowerCase();if(!db){setMessage('Newsletter connection is being configured.');return}const {error}=await db.from('newsletter_subscribers').insert({email,source:'filmcriqe-site'});setMessage(error?.code==='23505'?'You are already on the list.':error?'Please try again shortly.':'You’re on the list.');if(!error)e.currentTarget.reset()}return <form className={compact?'letter-form':''} onSubmit={submit}><label className="sr-only" htmlFor={compact?'letter-email':'newsletter-email'}>Email address</label><input id={compact?'letter-email':'newsletter-email'} name="email" type="email" placeholder="Your email address" required/><button className="button">Subscribe</button>{message&&<p className="metadata" role="status">{message}</p>}</form>}

export function ContactForm(){const [message,setMessage]=useState('');async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);if(!db){setMessage('The contact connection is being configured.');return}const payload={name:String(form.get('name')),email:String(form.get('email')).toLowerCase(),movie:String(form.get('movie')),social_handle:String(form.get('social')||''),message:String(form.get('message'))};const {error}=await db.from('review_requests').insert(payload);setMessage(error?'Please try again shortly.':'Thank you — your message has been received.');if(!error)e.currentTarget.reset()}return <form className="contact-form" onSubmit={submit}><Field label="Name" name="name"/><Field label="Email" name="email" type="email"/><Field label="Movie" name="movie"/><Field label="Instagram / social handle (optional)" name="social" required={false}/><Field label="Message" name="message" area/><button className="button">Send request</button>{message&&<p className="metadata" role="status">{message}</p>}</form>}
function Field({label,name,type='text',area=false,required=true}:{label:string;name:string;type?:string;area?:boolean;required?:boolean}){return <div className="form-field"><label htmlFor={name}>{label}</label>{area?<textarea id={name} name={name} required={required}/>:<input id={name} name={name} type={type} required={required}/>}</div>}
