export type Type = 'review'|'feature'|'essay'|'interview'|'hidden-gem'|'news'|'industry'|'awards'|'production';
export type Entry = { slug:string; type:Type; title:string; dek:string; date:string; year?:string; director?:string; genre?:string; author?:string; score?:number; premise?:string; body:string[]; cast?:string[]; hidden?:boolean; image?:string; imageAlt?:string; focalPoint?:string };
export const entries: Entry[] = [
 {slug:'after-the-last-light',type:'review',title:'After the Last Light',dek:'A patient, nocturnal chamber piece that trusts silence to do its most exacting work.',date:'2026-09-14',year:'2026',director:'Mara Ilyan',genre:'Drama',score:9.4,premise:'On the final night before a town is evacuated, two estranged sisters retrace the edges of a life they thought they had outgrown.',cast:['Noa Calder','Iris Venn','Hugo March'],body:['Some films announce their significance. This one listens for it. Mara Ilyan’s spare, beautiful drama unfolds at the tempo of a goodbye that neither of its central characters is prepared to name.','Its achievement is not simply restraint, but precision: each held shot makes room for a different kind of recognition. The camera does not pursue revelation; it waits for it.'],hidden:true,image:'/editorial/boat.jpg',imageAlt:'Black-and-white photograph of a man seated in a speedboat on the water.',focalPoint:'center'},
 {slug:'the-sound-of-weather',type:'feature',title:'The Sound of Weather',dek:'How filmmakers make climate audible before they make it visible.',date:'2026-09-07',author:'Avery Kim',body:['The weather in cinema is never only weather. It is pressure, memory, texture—an instrument tuned beneath dialogue.','For the sound designers who build these worlds, the first task is often subtraction. A storm becomes convincing when it is allowed to arrive through the room.'],image:'/editorial/city-window.jpg',imageAlt:'Black-and-white city skyline seen through a window.'},
 {slug:'looking-at-the-edges',type:'essay',title:'Looking at the Edges',dek:'On the moral charge of the frame and what films choose to leave unseen.',date:'2026-08-29',author:'Morgan Lee',body:['A frame is a decision made visible. Beyond its border are the stories a film has declined to tell, and inside it the attention it asks us to practise.','The richest films make this boundary feel alive: not a wall, but a question.'],image:'/editorial/hollywood.jpg',imageAlt:'Black-and-white photograph of the Hollywood sign at night.'},
 {slug:'the-work-of-listening',type:'interview',title:'The Work of Listening',dek:'A conversation with an independent filmmaker about silence, place and patient looking.',date:'2026-08-23',author:'Haile Ostrand',body:['For this conversation, FILMCRIQE asked what happens when a filmmaker treats silence not as absence, but as material.','The answer returned again and again to attention: to the room, the frame, and the people inside it.'],image:'/editorial/crosswalk.jpg',imageAlt:'Black-and-white overhead photograph of a car approaching a crosswalk.'},
 {slug:'paper-moons',type:'hidden-gem',title:'Paper Moons',dek:'An overlooked miniature about childhood, city streets, and private worlds.',date:'2026-08-18',year:'1998',director:'Leonie Hart',genre:'Coming-of-age',score:8.8,premise:'A quiet twelve-year-old spends one long summer mapping a neighborhood scheduled for redevelopment.',body:['Paper Moons moves with the peculiar confidence of a film that does not need to raise its voice. Its city is composed from alleys, laundromats, rain-slicked corners and the half-heard conversations of adults.','It deserves attention because it understands that smallness can be a form of scale.'],hidden:true,image:'/editorial/portrait.jpg',imageAlt:'Black-and-white portrait of a woman looking out of a car window.'}
];
export const labels:Record<Type,string>={review:'Film Review',feature:'Feature',essay:'Essay',interview:'Interview','hidden-gem':'Hidden Gem',news:'Film News',industry:'Industry',awards:'Awards',production:'Production'};
export function byType(type:Type){return entries.filter(e=>e.type===type)}
export function findEntry(slug:string,type?:Type){return entries.find(e=>e.slug===slug&&(!type||e.type===type))}
