import { createClient } from '@supabase/supabase-js';
import { Entry, Type, entries } from '@/lib/content';

const url=process.env.NEXT_PUBLIC_SUPABASE_URL;
const key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
const db=url&&key?createClient(url,key,{auth:{persistSession:false}}):null;

type DbContent={slug:string;type:Type;title:string;dek:string|null;published_at:string|null;release_year:number|null;director:string|null;genre:string|null;hero_path:string|null;hero_alt:string|null;body:unknown;tags:string[]|null;is_hidden_gem:boolean;review_meta:{overall?:number}|null};
function toEntry(item:DbContent):Entry { return {slug:item.slug,type:item.type,title:item.title,dek:item.dek||'',date:item.published_at?.slice(0,10)||'',year:item.release_year?.toString(),director:item.director||undefined,genre:item.genre||undefined,score:item.review_meta?.overall,body:Array.isArray(item.body)?item.body.map((block:{text?:string})=>block.text||'').filter(Boolean):[],hidden:item.is_hidden_gem||item.type==='hidden-gem',image:item.hero_path||undefined,imageAlt:item.hero_alt||undefined}; }
export async function publishedByType(type:Type){if(!db)return entries.filter(x=>x.type===type);const {data,error}=await db.from('content').select('slug,type,title,dek,published_at,release_year,director,genre,hero_path,hero_alt,body,tags,is_hidden_gem,review_meta').eq('status','published').eq('type',type).order('published_at',{ascending:false});return error||!data?.length?entries.filter(x=>x.type===type):(data as DbContent[]).map(toEntry)}
export async function publishedEntry(slug:string,type:Type){if(!db)return entries.find(x=>x.slug===slug&&x.type===type);const {data,error}=await db.from('content').select('slug,type,title,dek,published_at,release_year,director,genre,hero_path,hero_alt,body,tags,is_hidden_gem,review_meta').eq('status','published').eq('slug',slug).eq('type',type).maybeSingle();return !error&&data?toEntry(data as DbContent):entries.find(x=>x.slug===slug&&x.type===type)}
export async function searchPublished(query:string){const q=query.trim().toLowerCase();if(!q)return[];if(!db)return entries.filter(x=>JSON.stringify(x).toLowerCase().includes(q));const {data,error}=await db.from('content').select('slug,type,title,dek,published_at,release_year,director,genre,hero_path,hero_alt,body,tags,is_hidden_gem,review_meta').eq('status','published').or(`title.ilike.%${q}%,dek.ilike.%${q}%,director.ilike.%${q}%,genre.ilike.%${q}%`).order('published_at',{ascending:false});return error||!data?[]:(data as DbContent[]).map(toEntry)}
export async function homepageContent(){if(!db)return {featured:entries[1],latest:entries.slice(0,3),review:entries[0],gems:entries.filter(x=>x.type==='hidden-gem')};const select='slug,type,title,dek,published_at,release_year,director,genre,hero_path,hero_alt,body,tags,is_hidden_gem,review_meta';const [featuredResult,latestResult,reviewResult,gemsResult]=await Promise.all([db.from('content').select(select).eq('status','published').eq('is_featured',true).order('published_at',{ascending:false}).limit(1),db.from('content').select(select).eq('status','published').order('published_at',{ascending:false}).limit(3),db.from('content').select(select).eq('status','published').eq('type','review').order('published_at',{ascending:false}).limit(1),db.from('content').select(select).eq('status','published').or('is_hidden_gem.eq.true,type.eq.hidden-gem').order('published_at',{ascending:false}).limit(3)]);const featured=featuredResult.data?.[0]?toEntry(featuredResult.data[0] as DbContent):entries[1];const latest=latestResult.data?.length?(latestResult.data as DbContent[]).map(toEntry):entries.slice(0,3);const review=reviewResult.data?.[0]?toEntry(reviewResult.data[0] as DbContent):entries[0];const gems=gemsResult.data?.length?(gemsResult.data as DbContent[]).map(toEntry):entries.filter(x=>x.type==='hidden-gem');return {featured,latest,review,gems}}
